//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subkey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("subkey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BukyVede_Regular {
            get {
                object obj = ResourceManager.GetObject("BukyVede_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;keyboard fontfamily=&quot;RomanCyrillic Std&quot; fontsize=&quot;16&quot;&gt;
        ///    &lt;scheme name=&quot;Hist gramatyka&quot; fontfamily=&quot;RomanCyrillic Std&quot; fontsize=&quot;16&quot;&gt;
        ///        &lt;key&gt;
        ///            &lt;text&gt;Є&lt;/text&gt;
        ///            &lt;tooltip&gt;CYRILLIC CAPITAL LETTER UKRAINIAN IE&lt;/tooltip&gt;
        ///        &lt;/key&gt;
        ///        &lt;key&gt;
        ///            &lt;text&gt;Ѕ&lt;/text&gt;
        ///            &lt;tooltip&gt;CYRILLIC CAPITAL LETTER DZE&lt;/tooltip&gt;
        ///        &lt;/key&gt;
        ///        &lt;key&gt;
        ///            &lt;text&gt;Ꙁ&lt;/text&gt;
        ///            &lt;tooltip&gt;CYRILLIC CAPITAL LETTE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RomanCyrillic_Std {
            get {
                object obj = ResourceManager.GetObject("RomanCyrillic_Std", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
